enum LaporanEnum {
  // semua,
  // harianPit,
  // mingguanPit,
  // eventPit,
  // fokusPit,
  laporanData,
  laporan2Jam,
  laporanShift,
  laporanDaily,
  laporanWeekly,
  poskoTerpadu,
  boothPoskoTerpadu,
  poskoLapangan,
  poskoLain,
  // piketIm,
  kinerjaPelaporan,
}
