name: strategi_hub_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider_plus: ^7.1.0
  cupertino_icons: ^1.0.8
  dropdown_button2: 2.3.9
  easy_radio: ^0.0.3
  expandable: ^5.0.1
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.4.0
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.6.0
  carousel_slider: ^5.0.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.1
  iconly: ^1.0.1
  intl: ^0.19.0
  map_location_picker: ^1.3.3
  pagination_flutter: ^0.0.8
  path_provider: ^2.1.5
  shared_preferences: ^2.0.15
  syncfusion_flutter_charts: ^28.1.39
  syncfusion_flutter_datepicker: ^28.2.4
  json_annotation: ^4.9.0
  get_storage: ^2.1.1
  flutter_dotenv: ^5.2.1
  auto_mappr_annotation: ^2.3.0
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.2
  webview_flutter_wkwebview: ^3.18.1
  file_picker: ^9.0.0
  strategi_mobile_api:
    path: packages/data
  built_collection: ^5.1.1
  chewie: ^1.10.0
  video_player: ^2.9.2
  youtube_player_iframe: ^5.2.1
  dio: ^5.8.0+1
  provider: ^6.1.2
  internet_connection_checker_plus: ^2.7.1
  requests_inspector: ^4.2.1
  package_info_plus: ^8.3.0
  path: ^1.9.0
  permission_handler: ^11.4.0
  device_info_plus: ^11.3.0
  flutter_downloader: ^1.12.0
  open_file: ^3.5.10
  flutter_html: ^3.0.0
  dropdown_search: ^5.0.6

dev_dependencies:
  auto_mappr: ^2.8.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4

flutter_native_splash:
  image: assets/images/fav1.png
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  fullscreen: true
  android: true
  ios: true

  android_12:
    image: assets/images/fav1.png
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#FFFFFF"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/fav.png"
  adaptive_icon_foreground: "assets/images/fav-android.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - .env
