// Constants for field names
const String fieldIdEvent = 'idEvent';
const String fieldIdJenisPosko = 'idJenisPosko';
const String fieldNamaPosko = 'namaPosko';
const String fieldAlamatPosko = 'alamatPosko';
const String fieldUnitKerjaKoordinator = 'unitKerjaKoordinator';
const String fieldIdPesertaPosko = 'idPesertaPosko';
const String fieldKoordinatPosko = 'koordinatPosko';
const String fieldKetuaPosko = 'ketuaPosko';
const String fieldNoTelpKetuaPosko = 'noTelpKetuaPosko';
const String fieldPicPosko = 'picPosko';
const String fieldNoTelpPosko = 'noTelpPosko';
const String fieldMasaPantauAwal = 'masaPantauAwal';
const String fieldMasaPantauAkhir = 'masaPantauAkhir';
const String fieldTitikPantau = 'titikPantau';
const String fieldFokusPantau = 'fokusPantau';
const String fieldLampiran = 'lampiran';
